services:
    upstream:
        image: ghcr.io/linusdotmy/up.linus.my:latest
        ports:
            - "4002:3000"
        env_file: .env
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - upstream_network

    db:
        image: postgres:17-alpine
        environment:
            POSTGRES_USER: upstream
            POSTGRES_PASSWORD: upstream
            POSTGRES_DB: upstream
        volumes:
            - upstream_data:/var/lib/postgresql/data
        ports:
            - "4001:5432"
        restart: unless-stopped
        networks:
            - upstream_network

volumes:
    upstream_data:

networks:
    upstream_network:
        driver: bridge
